### ISSUE TITLE
Create on-page demo like mathjax.org or asciimath.org

### ISSUE THREAD

**Issue by ronaldtse** [plurimath/plurimath.github.io#17]
We need to use plurimath.js to create a live demo on the front page of plurimath.org.

The goal is to show:
* How plurimath renders math:
* Support for multiple input syntaxes (LaTeX math, Asciimath, etc)
* Support for multiple output syntaxes (select the output format)
* Provide the "math rendering tree" to show how the formula is parsed.

https://www.mathjax.org/#demo

<img width="598" alt="Screenshot 2023-10-26 at 12 02 40 PM" src="https://github.com/plurimath/plurimath.github.io/assets/11865/1ef0ba9a-0afe-4711-9587-a0eccf9e927b">

http://asciimath.org

<img width="628" alt="Screenshot 2023-10-26 at 12 02 54 PM" src="https://github.com/plurimath/plurimath.github.io/assets/11865/ebae5d37-c47d-4d99-a5b1-5db447a4f24c">

Maybe we can do a "Google Translate" kind of conversion interface:

<img width="651" alt="Screenshot 2023-10-26 at 12 05 22 PM" src="https://github.com/plurimath/plurimath.github.io/assets/11865/d47c0055-ca99-47b9-9df5-052fe115ca76">

**Comment by ronaldtse** [comment]
@webdev778 thanks for adding the demo page. Could you help add a placeholder formula so it shows some rendering on load?

The preview should be displayed in MathML. In case the MathML isn't renderable by the browser, we need to load MathJax to render it.

**Comment by ronaldtse** [comment]
Also, let's not require the user to "click" on the "Convert" button, but automatically update whenever the user "change"s the input box. Refer to the behavior of http://asciimath.org

**Comment by webdev778** [comment]
Yeah, it'd be better. will update it

**Comment by webdev778** [comment]
math rendering tree

`
  describe ".to_display(:asciimath)" do
    subject(:formula) { Plurimath::Math.parse(exp, :asciimath).to_display(:asciimath) }

    context "AsciiMath Math zone representation of sin and simple equation #1" do
      let(:exp) { "sum_3^1 sintheta" }

      it 'should puts Math zone representation of sample example #1' do
        expected_value = <<~MATHZONE
          |_ Math zone
            |_ "sum_(3)^(1) sintheta"
               |_ "sum_(3)^(1) sintheta" summation
                  |_ "3" subscript
                  |_ "1" supscript
                  |_ "sintheta" term
                     |_ "sintheta" function apply
                        |_ "sin" function name
                        |_ "theta" argument
        MATHZONE
        expect(formula).to eql(expected_value)
      end
    end
`
