### ISSUE TITLE
Add preview section with vanilla MathML vs MathJax

### ISSUE THREAD

**Issue by ronaldtse** [plurimath/plurimath.github.io#30]
From @suleman-uzair:

It seems like the issue is just with how the Math is shown on different web browsers.

The equation looks right in **Firefox** but not in **Google Chrome**.

We’re using **MathML** without using **MathJax** Library to show the math in [plurimath.org](http://plurimath.org/), and it seems like **Google Chrome** doesn’t fully support it yet.

We use either **MathJax** or another library in [plurimath.org](http://plurimath.org/), to show the Math so it looks the same in all browsers.

1. **Google Chrome**
![Screenshot from 2024-02-15 13-22-33](https://github.com/plurimath/plurimath/assets/96812483/afd3a9d5-d705-4a4a-8ea3-104ec280f052)

2. **FireFox**
![Screenshot from 2024-02-15 13-27-12](https://github.com/plurimath/plurimath/assets/96812483/eb8d46a6-cf6e-423a-af8c-941867b748e5)

3. **MathJax**
![Screenshot from 2024-02-15 12-38-57](https://github.com/plurimath/plurimath/assets/96812483/54f85445-fb25-44bb-b0dd-97d3d345cebb)

_Originally posted by @suleman-uzair in https://github.com/plurimath/plurimath/issues/214#issuecomment-1945641829_

**Comment by ronaldtse** [comment]
We should add two previews for plurimath render output:
* vanilla MathML (browser support)
* MathML rendered using MathJax

**Comment by suleman-uzair** [comment]
> We should add two previews for plurimath render output:
> 
> * vanilla MathML (browser support)
> * MathML rendered using MathJax

@ronaldtse 

Will work on it after finalizing current tasks.
Should we display both presentations simultaneously (vanilla MathML and MathML using MathJax), or would it be better to incorporate a dropdown menu similar to the one used for language changes?

**Comment by ronaldtse** [comment]
> Should we display both presentations simultaneously (vanilla MathML and MathML using MathJax), or would it be better to incorporate a dropdown menu similar to the one used for language changes?

A dropdown could work. But we need to load MathJax anyway. Maybe use MathJax as the default, and then "native browser rendering" as an option.

**Comment by ronaldtse** [comment]
This is fixed in #39. Thanks @suleman-uzair !
