### ISSUE TITLE
Add description for Plurimath

### ISSUE THREAD

**Issue by ronaldtse** [plurimath/plurimath.github.io#5]
What is plurimath?

How to use plurimath?

Examples of using plurimath?
* sample formulas

**Comment by ronaldtse** [comment]
@suleman-uzair can you help check this? Thanks.

**Comment by suleman-uzair** [comment]
@ronaldtse 

1. I'm currently working on https://github.com/plurimath/plurimath/pull/178, If this task is urgent I'll work on it right away.
2. Do I have to add a page or blog posts of the details?

**Comment by suleman-uzair** [comment]
@ronaldtse, Could you please add me as a contributor to the repository? Thank you!
